export const fileTypes = {
  audio: new Set(["mp3", "wav", "aac", "flac", "ogg", "m4a", "wma"]),
  video: new Set(["mp4", "mkv", "avi", "mov", "wmv", "flv", "webm", "m4v"]),
  image: new Set(["jpeg", "jpg", "png", "gif", "bmp", "tiff", "svg", "webp"]),
  apps: new Set(["exe", "deb", "apk", "dmg", "msi", "sh", "bin", "rpm"]),
  archives: new Set(["zip", "rar", "7z", "tar", "gz", "bz2", "xz", "iso"]),
  documents: new Set([
    "pdf",
    "doc",
    "docx",
    "xls",
    "xlsx",
    "ppt",
    "pptx",
    "txt",
    "odt",
    "rtf",
  ]),
  code: new Set([
    "html",
    "css",
    "js",
    "ts",
    "json",
    "xml",
    "java",
    "py",
    "cpp",
    "c",
    "php",
    "rb",
  ]),
};
